import './globals.css'
import './embla.css'
import { getPayload } from 'payload'
import payloadConfig from '@/payload.config'
import { HeaderComponent } from '@/components/header-component'
import { Footer } from '@/components/footer'
import { CheckoutSidebarProvider } from './checkout-sidebar-context'
import { CheckoutSidebar } from '@/components/checkout-sidebar'
import { CartCountProvider } from './cart-count-context'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const payload = await getPayload({ config: payloadConfig });
  const profile = await payload.findGlobal({
    slug: 'profile',
    depth: 1,
  })

  return (
    <html lang="en">
      <body>
        <CheckoutSidebarProvider>
          <CartCountProvider>
            <div className='relative'>
              <div className='min-h-view'>
                <HeaderComponent profile={profile} />
                {children}
              </div>
              <Footer profile={profile} />
              <CheckoutSidebar />
            </div>
          </CartCountProvider>
        </CheckoutSidebarProvider>
      </body>
    </html>
  )
}
